#!/usr/bin/env python3
import os
import datetime
import sqlite3
from fpdf import FPDF
import sys

# Add the server directory to sys.path to import database_manager
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), 'server')))
import database_manager
import config

class SentinelReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Security Audit Report', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, f'Generated on: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by FTMS Sentinel', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, title, 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()

    def violation_table(self, logs):
        # Table Header
        self.set_font('Arial', 'B', 9)
        self.set_fill_color(200, 220, 255)
        self.cell(35, 7, 'Timestamp', 1, 0, 'C', 1)
        self.cell(40, 7, 'Event Type', 1, 0, 'C', 1)
        self.cell(60, 7, 'File Path', 1, 0, 'C', 1)
        self.cell(30, 7, 'Risk Level', 1, 1, 'C', 1)

        # Table Rows
        self.set_font('Arial', '', 8)
        for log in logs:
            # Shorten message if too long
            path = str(log['file_path'])
            if len(path) > 35: path = "..." + path[-32:]
            
            self.cell(35, 6, str(log['timestamp']), 1)
            self.cell(40, 6, str(log['action']), 1)
            self.cell(60, 6, path, 1)
            self.cell(30, 6, str(log['risk_level']), 1, 1, 'C')
        self.ln()

def generate(event_data=None):
    """
    Main entry point for generating the PDF report.
    Returns success status and file URL.
    """
    try:
        # Create reports directory
        report_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'reports')
        os.makedirs(report_dir, exist_ok=True)
        
        timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        report_filename = f"Security_Audit_Report_{timestamp}.pdf"
        report_path = os.path.join(report_dir, report_filename)

        # Connect to DB to get stats
        conn = database_manager.get_db_connection()
        try:
            # 1. Executive Summary Stats
            total_events = conn.execute("SELECT COUNT(*) FROM logs").fetchone()[0]
            start_time = conn.execute("SELECT MIN(timestamp) FROM logs").fetchone()[0] or "N/A"
            end_time = conn.execute("SELECT MAX(timestamp) FROM logs").fetchone()[0] or "N/A"
            violation_count = conn.execute("SELECT COUNT(*) FROM logs WHERE risk_level IN ('HIGH', 'CRITICAL')").fetchone()[0]
            
            # 2. Violation Data (Last 50 for the table)
            logs = conn.execute("SELECT * FROM logs WHERE risk_level IN ('HIGH', 'CRITICAL') ORDER BY id DESC LIMIT 50").fetchall()
            
            # 3. Top Active Users
            top_users = conn.execute("SELECT username, COUNT(*) as count FROM logs GROUP BY username ORDER BY count DESC LIMIT 5").fetchall()
            
        finally:
            conn.close()

        # Initialize PDF
        pdf = SentinelReport()
        pdf.add_page()
        
        # Auditor info (from event_data if available)
        auditor = "System Admin"
        if event_data and 'username' in event_data:
            auditor = event_data['username']

        # Title Section
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 5, f'Date: {datetime.datetime.now().strftime("%Y-%m-%d")}', 0, 1)
        pdf.cell(0, 5, 'System: Secure File Transfer Monitor', 0, 1)
        pdf.cell(0, 5, f'Auditor: {auditor}', 0, 1)
        pdf.ln(5)
        pdf.cell(0, 0, '', 'T', 1) 
        pdf.ln(10)

        # 1. Executive Summary
        pdf.chapter_title('1. Executive Summary')
        summary = (
            f"- Total Events: {total_events}\n"
            f"- Start Time: {start_time}\n"
            f"- End Time: {end_time}\n"
            f"- Total Violations Detected: {violation_count}"
        )
        pdf.chapter_body(summary)

        # 2. Violation Summary
        pdf.chapter_title('2. Violation Summary')
        if logs:
            pdf.violation_table(logs)
        else:
            pdf.chapter_body("No high-risk violations detected in the logs.")

        # 3. Top Active Users
        pdf.chapter_title('3. Top Active Users')
        user_list = ""
        for user in top_users:
            user_list += f"- {user['username']}: {user['count']} Events\n"
        if not user_list: user_list = "No user activity logged."
        pdf.chapter_body(user_list)

        # 5. Recommendations
        pdf.chapter_title('5. Recommendations')
        recs = [
             "1. Investigate the unauthorized moves listed in the Violation Summary.",
             "2. Restrict write permissions on Public folders for sensitive groups.",
             "3. Deploy blocking agents on USB ports."
        ]
        if violation_count > 10:
            recs.append("4. CRITICAL: High frequency of violations detected. Urgent security audit required.")
        
        pdf.chapter_body("\n".join(recs))

        # Finalize
        pdf.output(report_path)
        
        return {
            "status": "success",
            "file_url": f"/downloads/{report_filename}",
            "generated_at": datetime.datetime.now().isoformat()
        }

    except Exception as e:
        print(f"Error generating PDF: {e}")
        return {
            "status": "error",
            "message": str(e)
        }

def generate_single_report(event_data, event_id):
    """
    Generates a PDF report for a single high-risk event.
    Used by the auto-reporting feature in monitor.py.
    """
    try:
        report_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'reports')
        os.makedirs(report_dir, exist_ok=True)
        report_path = os.path.join(report_dir, f"Security_Alert_{event_id}.pdf")

        pdf = SentinelReport()
        pdf.add_page()
        
        pdf.set_font('Arial', 'B', 16)
        pdf.set_text_color(220, 0, 0)
        pdf.cell(0, 10, 'CRITICAL SECURITY ALERT', 0, 1, 'C')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)

        pdf.chapter_title('Event Details')
        details = (
            f"Event ID: {event_id}\n"
            f"Timestamp: {event_data.get('timestamp')}\n"
            f"Event Type: {event_data.get('event_type')}\n"
            f"Risk Level: {event_data.get('risk_level')}\n"
            f"Action/Reason: {event_data.get('reason')}"
        )
        pdf.chapter_body(details)

        pdf.chapter_title('Target Information')
        target = f"File Path: {event_data.get('file_path')}"
        pdf.chapter_body(target)

        pdf.chapter_title('System Recommendation')
        pdf.chapter_body("IMMEDIATE ACTION REQUIRED: The system has detected a high-risk event. Please verify the legitimacy of this operation and restrict user access if necessary.")

        pdf.output(report_path)
        return True
    except Exception as e:
        print(f"Failed to generate single report: {e}")
        return False

if __name__ == "__main__":
    # Test generation
    res = generate({"username": "TestAdmin"})
    print(res)
